name: Deploy to server by ssh

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: '21.x' # Utilisez la version 16.x ou une version compatible.

      - name: Clear npm cache and Node.js
        run: |
          npm cache clean --force
          sudo npm cache verify
          sudo npm cache clear --force
          
      - name: Deploy to Production
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod'
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < deploy_prod.sh
